### ISSUE TITLE
Add progress bar

### ISSUE THREAD

**Issue by ChrisWiegman** [petenelson/wp-any-ipsum#13]
A progress bar for output (instead of the scrolling output) would be awesome (I could probably make this in a PR if needed).

**Comment by petenelson** [comment]
Will be committed shortly

![image](https://cloud.githubusercontent.com/assets/1757075/11518457/f8451194-9856-11e5-8215-191b10d4a67c.png)

**Comment by petenelson** [comment]
Released up to the repo
